project:
  type: website
  output-dir: docs
  
website:
  title: "João Pedro Donadio"
  navbar:
    title: JP Donadio
    background: "primary"
    left:
      - href: index.qmd
        text: Home
      - text: Portfolio
        menu:
          - href: projects.qmd
            text: "All Projects"
          - href: metaanalysis.qmd
            text: "Meta-analysis Calves"
          - href: watercalves.qmd
            text: "Experiment Water for Calves"
      - href: cv.qmd
        text: Curriculum vitæ
     
    right:
      - href: index.qmd#contact
        icon: envelope  
        text: Contact Me
    
format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    include-after-body: footer.html

editor: visual

